## Arrays vs Lists

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [5]:
for e in L:
    print(e)

1
2
3


In [8]:
for e in A:
    print(e)

1
2
3


In [11]:
L.append(4)

In [29]:
L

[1, 2, 3, 4, 4, 4]

In [30]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

#### Concatenation

In [14]:
L + [5]

[1, 2, 3, 4, 4, 4, 5]

#### Broadcasting

In [16]:
A + np.array([4])

array([5, 6, 7])

#### Note: Arrays are fixed. New elements cannot be added to them unlike lists. However, broadcasting works i.e adding to all the elements in the array. This is called vector addition and the arrays/vectors must always be of equal size.

In [17]:
A + np.array([4,5,6])

array([5, 7, 9])

#### Scalar Multiplication

In [20]:
2 * A

array([2, 4, 6])

In [21]:
2 * L

[1, 2, 3, 4, 4, 4, 1, 2, 3, 4, 4, 4]

#### Note: Scalar multilication in lists works by repitition but by multiplication in arrays

In [22]:
L + L

[1, 2, 3, 4, 4, 4, 1, 2, 3, 4, 4, 4]

#### Adding to each element in List L

In [24]:
L2 = []
for e in L:
    L2.append(e+3)

In [25]:
L2

[4, 5, 6, 7, 7, 7]

In [26]:
L2 = [e + 3 for e in L]

In [27]:
L2

[4, 5, 6, 7, 7, 7]

In [28]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [32]:
L2 = [e**2 for e in L]

In [33]:
L2

[1, 4, 9, 16, 16, 16]

In [34]:
A**2

array([1, 4, 9])

In [35]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [36]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [37]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [38]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

#### Note: A list looks like an array but works more like a generative data structure, while a numpy array exists specifically to do Math