## Matrices

In [5]:
import numpy as np

In [1]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [2]:
L[0]

[1, 2]

In [3]:
L[0][1]

2

In [8]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [9]:
A[0][1]

2

In [10]:
A[0,1]

2

#### Selecting a column from the matrix

In [11]:
A[:, 0]

array([1, 3])

#### Selecting a row from the matrix

In [12]:
A[0]

array([1, 2])

In [13]:
A.T

array([[1, 3],
       [2, 4]])

In [14]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [15]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

#### Matrix Multiplication

In [19]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
A

array([[1, 2],
       [3, 4]])

In [24]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [28]:
np.linalg.det(A)

-2.0000000000000004

In [29]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Inverse * Dot = Identity

In [31]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [33]:
np.trace(A)

5

#### The diag() function is overloaded. If you put in a vector, you get a matrix. If you put in a matrix, you get a vector

#### Calling diag on a matrix

In [36]:
np.diag(A)

array([1, 4])

#### Calling diag on a list

In [35]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [37]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [42]:
Lam, V = np.linalg.eig(A)

#### Checking whether the zero with eigen value multiplied by the zero with eigen vector is equal to A times the zero with the eigen vector

In [40]:
A

array([[1, 2],
       [3, 4]])

The first column of the eigen vector

In [44]:
V[:,0]

array([-0.82456484,  0.56576746])

The first column of the eigen value which is just a value

In [45]:
Lam[0]

-0.3722813232690143

Checking

In [47]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [49]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

Best way to compare two arrays in numpy is to use the allclose function

In [50]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [51]:
np.allclose(V @ np.diag(Lam), A @ V)

True